### ISSUE TITLE
Add docs/support for other Dex connectors

### ISSUE THREAD

**Issue by stoehdoi** [litmuschaos/litmus-docs#173]
## FEATURE REQUEST?

Dex also supports other connectors besides GitHub and Google. I've tried to use Microsoft Azure AD and it is working fine. Can we add a note that other connectors are supported too or include them in the sample configuration. 

This is a working configuration for Microsoft connector
```
    connectors:
      - type: microsoft
        id: microsoft
        name: Microsoft
        config:
          clientID: # Add your Microsoft Azure Client ID here
          clientSecret: # Add your Microsoft Azure Client Secret here
          redirectURI: http://<NODE_IP>:32000/callback
          tenant: # Add your Microsoft Azure Tenant ID here (if applicable)
```
