### ISSUE TITLE
Prometheus Helm release name doesn't match

### ISSUE THREAD

**Issue by jordifebrer** [litmuschaos/litmus-docs#192]
## BUG REPORT

**What happened**:
The release name `prom` on Prometheus helm installation details on this page: https://docs.litmuschaos.io/docs/integrations/prometheus/#prometheus-community-version-helm---kube-prometheus-stack-with-pod-monitor doesn't match with the provided PodMonitor release name `prometheus-stack`.

The service discovery never discover the podmonitor because is looking for a podmonitor with a label release: prom instead of release: prometheus-stack

**What you expected to happen**:
```
helm install prom prometheus-community/kube-prometheus-stack --namespace monitoring
```
should be

```
helm install prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring
```

**How to reproduce it (as minimally and precisely as possible)**:
1) Run:
```
helm install prom prometheus-community/kube-prometheus-stack --namespace monitoring
```
2) Apply the PodMonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chaos-exporter-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: chaos-exporter
  namespaceSelector:
    matchNames:
      - litmus
  podMetricsEndpoints:
    - port: tcp
    - interval: 1s
      metricRelabelings:
        - targetLabel: instance
          replacement: 'chaos-exporter-service'
```

**Anything else we need to know?**:
I suggest using a release name `prometheus-stack` with helm install because is following the naming convention used in the rest of the repository instead of changing the release name of the PodMonitor to `prom`.
